sudo: false
language: node_js
node_js:
    - "10"
before_script:
    - npm install -g yarn
install:
    - yarn install &&  yarn bootstrap
script:
    - yarn build-fragments
    - yarn start-fragments
    - yarn watch-fragments
cache:
    yarn: true
    directories:
        - node_modules
